import 'server-only';
import { claimOf } from '@/lib/api';
import { upsert } from './directory';
import { store } from './store';
const LEGACY=(process.env.LEGACY_API_BASE||'').replace(/\/$/,'');
function claims(token){try{const p=String(token).split('.')[1];return p?JSON.parse(Buffer.from(p,'base64url').toString('utf8')):null}catch{return null}}
async function getJson(token,path){const r=await fetch(LEGACY+path,{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)return null;return r.json()}
export async function migrateLegacyLogin(login,password){if(!LEGACY)return null;try{const r=await fetch(LEGACY+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({emailOrPhone:login,password,rememberMe:true}),cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)return null;const body=await r.json();const token=body?.token||body?.accessToken||body?.data?.token||body?.data?.accessToken;if(!token)return null;const c=claims(token)||{},u=body?.user||body?.data||{};const email=u.email||claimOf(c,'email')||(/@/.test(login)?login:'');const phone=u.phone||u.phoneNumber||(/05\d{8}/.test(login)?login:'');const role=claimOf(c,'role')||u.role||u.userRole||'Patient';const fullName=u.fullName||u.name||claimOf(c,'name')||'';let profile=null,drugRequests=null;try{const endpoint={Doctor:'/api/doctors/me',Hospital:'/api/facilities/me',Pharmacy:'/api/pharmacies/me'}[role];if(endpoint)profile=await getJson(token,endpoint);drugRequests=await getJson(token,'/api/drugrequests/my')}catch{}return {fullName,email,phone,role,legacyToken:token,profile,drugRequests};}catch(e){console.error('[shifa] legacy migration failed',e);return null}}
export async function migrateLegacyData(localUser,migrated){if(!migrated)return;try{const profile=migrated.profile?.data||migrated.profile?.result||migrated.profile?.item||migrated.profile;if(profile){const collection=migrated.role==='Doctor'?'doctors':migrated.role==='Pharmacy'?'pharmacies':migrated.role==='Hospital'?'facilities':null;if(collection){const existing=(await store.read(collection)).find(x=>String(x.userId||'')===String(localUser.id)||String(x.email||'').toLowerCase()===String(localUser.email||'').toLowerCase());const record={...profile,userId:localUser.id,email:profile.email||localUser.email,id:existing?.id||'local_'+localUser.id};await upsert(collection,record);}}const list=Array.isArray(migrated.drugRequests?.data)?migrated.drugRequests.data:Array.isArray(migrated.drugRequests)?migrated.drugRequests:[];if(list.length)await store.update('drug-requests',items=>{const existingIds=new Set(items.filter(x=>String(x.userId)===String(localUser.id)).map(x=>String(x.id)));const copied=list.filter(x=>!existingIds.has(String(x.id))).map(x=>({...x,id:String(x.id||store.newId('drug')),userId:localUser.id}));return {items:[...items,...copied],result:true}});}catch(e){console.error('[shifa] legacy data copy failed',e)}}
