/* Module 9 — Arabic ↔ English medicine names for matching.

   Each entry is one product: its names in both scripts, plus the active
   ingredient (`generic`). Two names in the same entry are the same
   medicine. Two entries with the same `generic` are different brands of
   the same ingredient: offered as a match, but flagged for the pharmacist
   to confirm. Spellings are compared after letter folding (أ/إ/آ → ا,
   ة → ه, ى → ي), so each spelling only needs listing once. */

export const MEDICINE_ALIASES = [
  // Pain & fever
  { names: ['Panadol', 'بنادول', 'بانادول'], generic: 'paracetamol' },
  { names: ['Paracetamol', 'باراسيتامول', 'براسيتامول', 'Acetaminophen', 'اسيتامينوفين'], generic: 'paracetamol' },
  { names: ['Revanin', 'ريفانين'], generic: 'paracetamol' },
  { names: ['Acamol', 'اكامول'], generic: 'paracetamol' },
  { names: ['Tylenol', 'تايلينول'], generic: 'paracetamol' },
  { names: ['Adol', 'ادول'], generic: 'paracetamol' },
  { names: ['Ibuprofen', 'ايبوبروفين', 'ابوبروفين'], generic: 'ibuprofen' },
  { names: ['Brufen', 'بروفين'], generic: 'ibuprofen' },
  { names: ['Advil', 'ادفيل'], generic: 'ibuprofen' },
  { names: ['Nurofen', 'نوروفين'], generic: 'ibuprofen' },
  { names: ['Diclofenac', 'ديكلوفيناك'], generic: 'diclofenac' },
  { names: ['Voltaren', 'فولتارين'], generic: 'diclofenac' },
  { names: ['Cataflam', 'كتافلام', 'كاتافلام'], generic: 'diclofenac' },
  { names: ['Aspirin', 'اسبرين', 'اسبيرين'], generic: 'aspirin' },
  { names: ['Aspocid', 'اسبوسيد'], generic: 'aspirin' },
  { names: ['Tramadol', 'ترامادول'], generic: 'tramadol' },

  // Antibiotics
  { names: ['Amoxicillin', 'اموكسيسيلين', 'اموكسيسلين', 'اموكسيل'], generic: 'amoxicillin' },
  { names: ['Augmentin', 'اوجمنتين', 'اوغمنتين', 'اوجمانتين'], generic: 'amoxicillin-clavulanate' },
  { names: ['Amoxiclav', 'اموكسيكلاف'], generic: 'amoxicillin-clavulanate' },
  { names: ['Azithromycin', 'ازيثرومايسين'], generic: 'azithromycin' },
  { names: ['Zithromax', 'زيثروماكس'], generic: 'azithromycin' },
  { names: ['Ciprofloxacin', 'سيبروفلوكساسين'], generic: 'ciprofloxacin' },
  { names: ['Ciprobay', 'سيبروباي'], generic: 'ciprofloxacin' },
  { names: ['Cephalexin', 'سيفالكسين', 'سيفاليكسين'], generic: 'cephalexin' },
  { names: ['Keflex', 'كيفلكس'], generic: 'cephalexin' },
  { names: ['Ceftriaxone', 'سيفترياكسون'], generic: 'ceftriaxone' },
  { names: ['Rocephin', 'روسيفين'], generic: 'ceftriaxone' },
  { names: ['Metronidazole', 'ميترونيدازول'], generic: 'metronidazole' },
  { names: ['Flagyl', 'فلاجيل', 'فلاجل'], generic: 'metronidazole' },
  { names: ['Doxycycline', 'دوكسيسيكلين'], generic: 'doxycycline' },
  { names: ['Clarithromycin', 'كلاريثرومايسين'], generic: 'clarithromycin' },
  { names: ['Klacid', 'كلاسيد'], generic: 'clarithromycin' },

  // Diabetes
  { names: ['Insulin', 'انسولين'], generic: 'insulin' },
  { names: ['Insulin Glargine', 'انسولين جلارجين', 'انسولين غلارجين', 'جلارجين'], generic: 'insulin-glargine' },
  { names: ['Lantus', 'لانتوس', 'Lantus Solostar', 'لانتوس سولوستار'], generic: 'insulin-glargine' },
  { names: ['Insulin Aspart', 'انسولين اسبارت'], generic: 'insulin-aspart' },
  { names: ['NovoRapid', 'نوفورابيد', 'نوفو رابيد'], generic: 'insulin-aspart' },
  { names: ['Mixtard', 'ميكستارد'], generic: 'insulin-mixed' },
  { names: ['Metformin', 'ميتفورمين'], generic: 'metformin' },
  { names: ['Glucophage', 'جلوكوفاج', 'غلوكوفاج'], generic: 'metformin' },
  { names: ['Gliclazide', 'جليكلازايد'], generic: 'gliclazide' },
  { names: ['Diamicron', 'دياميكرون'], generic: 'gliclazide' },
  { names: ['Glimepiride', 'جليميبرايد'], generic: 'glimepiride' },
  { names: ['Amaryl', 'اماريل'], generic: 'glimepiride' },

  // Heart & blood pressure
  { names: ['Amlodipine', 'املوديبين'], generic: 'amlodipine' },
  { names: ['Norvasc', 'نورفاسك'], generic: 'amlodipine' },
  { names: ['Enalapril', 'اينالابريل', 'انالابريل'], generic: 'enalapril' },
  { names: ['Captopril', 'كابتوبريل'], generic: 'captopril' },
  { names: ['Lisinopril', 'ليسينوبريل'], generic: 'lisinopril' },
  { names: ['Losartan', 'لوسارتان'], generic: 'losartan' },
  { names: ['Cozaar', 'كوزار'], generic: 'losartan' },
  { names: ['Valsartan', 'فالسارتان'], generic: 'valsartan' },
  { names: ['Diovan', 'ديوفان'], generic: 'valsartan' },
  { names: ['Bisoprolol', 'بيسوبرولول'], generic: 'bisoprolol' },
  { names: ['Concor', 'كونكور'], generic: 'bisoprolol' },
  { names: ['Atenolol', 'اتينولول'], generic: 'atenolol' },
  { names: ['Furosemide', 'فوروسيمايد', 'فيوروسيمايد'], generic: 'furosemide' },
  { names: ['Lasix', 'لازكس', 'لازيكس'], generic: 'furosemide' },
  { names: ['Hydrochlorothiazide', 'هيدروكلوروثيازايد'], generic: 'hydrochlorothiazide' },
  { names: ['Atorvastatin', 'اتورفاستاتين'], generic: 'atorvastatin' },
  { names: ['Lipitor', 'ليبيتور'], generic: 'atorvastatin' },
  { names: ['Simvastatin', 'سيمفاستاتين'], generic: 'simvastatin' },
  { names: ['Clopidogrel', 'كلوبيدوجريل'], generic: 'clopidogrel' },
  { names: ['Plavix', 'بلافيكس'], generic: 'clopidogrel' },
  { names: ['Warfarin', 'وارفارين'], generic: 'warfarin' },

  // Stomach
  { names: ['Omeprazole', 'اوميبرازول'], generic: 'omeprazole' },
  { names: ['Losec', 'لوسيك'], generic: 'omeprazole' },
  { names: ['Esomeprazole', 'ايزوميبرازول'], generic: 'esomeprazole' },
  { names: ['Nexium', 'نيكسيوم'], generic: 'esomeprazole' },
  { names: ['Pantoprazole', 'بانتوبرازول'], generic: 'pantoprazole' },
  { names: ['Controloc', 'كونترولوك'], generic: 'pantoprazole' },
  { names: ['Ranitidine', 'رانيتيدين'], generic: 'ranitidine' },
  { names: ['Zantac', 'زانتاك'], generic: 'ranitidine' },
  { names: ['Metoclopramide', 'ميتوكلوبراميد'], generic: 'metoclopramide' },
  { names: ['Primperan', 'بريمبيران'], generic: 'metoclopramide' },
  { names: ['Domperidone', 'دومبيريدون'], generic: 'domperidone' },
  { names: ['Motilium', 'موتيليوم'], generic: 'domperidone' },
  { names: ['ORS', 'محلول الجفاف', 'املاح الجفاف', 'اورس'], generic: 'oral-rehydration-salts' },

  // Respiratory & allergy
  { names: ['Salbutamol', 'سالبوتامول'], generic: 'salbutamol' },
  { names: ['Ventolin', 'فنتولين'], generic: 'salbutamol' },
  { names: ['Budesonide', 'بوديزونايد'], generic: 'budesonide' },
  { names: ['Pulmicort', 'بولميكورت'], generic: 'budesonide' },
  { names: ['Seretide', 'سيريتايد'], generic: 'fluticasone-salmeterol' },
  { names: ['Symbicort', 'سيمبيكورت'], generic: 'budesonide-formoterol' },
  { names: ['Montelukast', 'مونتيلوكاست'], generic: 'montelukast' },
  { names: ['Singulair', 'سينجولير'], generic: 'montelukast' },
  { names: ['Loratadine', 'لوراتادين'], generic: 'loratadine' },
  { names: ['Claritine', 'Claritin', 'كلاريتين'], generic: 'loratadine' },
  { names: ['Cetirizine', 'سيتيريزين'], generic: 'cetirizine' },
  { names: ['Zyrtec', 'زيرتك'], generic: 'cetirizine' },

  // Neuro & mental health
  { names: ['Carbamazepine', 'كاربامازيبين'], generic: 'carbamazepine' },
  { names: ['Tegretol', 'تيجريتول'], generic: 'carbamazepine' },
  { names: ['Valproate', 'فالبروات', 'Sodium Valproate'], generic: 'valproate' },
  { names: ['Depakine', 'ديباكين'], generic: 'valproate' },
  { names: ['Levetiracetam', 'ليفيتيراسيتام'], generic: 'levetiracetam' },
  { names: ['Keppra', 'كيبرا'], generic: 'levetiracetam' },
  { names: ['Phenytoin', 'فينيتوين'], generic: 'phenytoin' },
  { names: ['Sertraline', 'سيرترالين'], generic: 'sertraline' },
  { names: ['Fluoxetine', 'فلوكستين', 'فلوكسيتين'], generic: 'fluoxetine' },
  { names: ['Prozac', 'بروزاك'], generic: 'fluoxetine' },

  // Thyroid, steroids, vitamins, supplements
  { names: ['Levothyroxine', 'ليفوثيروكسين'], generic: 'levothyroxine' },
  { names: ['Eltroxin', 'التروكسين'], generic: 'levothyroxine' },
  { names: ['Euthyrox', 'يوثيروكس'], generic: 'levothyroxine' },
  { names: ['Prednisolone', 'بريدنيزولون'], generic: 'prednisolone' },
  { names: ['Dexamethasone', 'ديكساميثازون'], generic: 'dexamethasone' },
  { names: ['Folic Acid', 'حمض الفوليك', 'فوليك اسيد'], generic: 'folic-acid' },
  { names: ['Ferrous Sulfate', 'كبريتات الحديد', 'حديد', 'Iron'], generic: 'iron' },
  { names: ['Vitamin D', 'فيتامين د'], generic: 'vitamin-d' },
  { names: ['Calcium', 'كالسيوم'], generic: 'calcium' }
];
